### ISSUE TITLE
ValueError: invalid padding byte

### ISSUE THREAD

**Issue by wjinlong** [borisbabic/browser_cookie3#140]
hi, I got one error as follows.

```
Traceback (most recent call last):
  File "/Users/user/browser_cookie3/__init__.py", line 395, in _decrypt
    decrypted += cipher.feed()
  File "/Users/user/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/Users/user/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/Users/user/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte
```

**method: strip_PKCS7_padding
_get_byte return pad=62 after raise ValueError("invalid padding byte")**

### Version Info
Apple M1 Pro
macOS version 12.5.1
Microsoft Edge	107.0.1418.35 (release) (arm64) 
browser-cookie3    0.16.2

*May be related to the Edge upgrade.*

**Comment by wjinlong** [comment]
I tried "Fresh cookie files", it's run successfully. 
How should I fix my old cookies?

**Comment by wjinlong** [comment]
The cookie ( '~/Library/Application Support/Microsoft Edge/Default/Cookies') has some problem. I remove it. 
This path '~/Library/Application Support/Microsoft Edge/Profile */Cookies' can decrypt correctly.
