### ISSUE TITLE
AssertionError: Page format changed.

### ISSUE THREAD

**Issue by LaughlinJames** [borisbabic/browser_cookie3#144]
Please let me know if you need more information. I'm running a tool that my team owns. It uses your library and I'm getting this error.

TBH I feel a little silly just giving you the stack trace and saying "fix me" but the team that wrote the tool has abdicated responsibility so I'm hoping you can help point me in a direction that might lead to a resolution.

Thanks.

Traceback (most recent call last):
  File "/usr/local/bin/amstool", line 8, in <module>
    sys.exit(base_commands())
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/commands/auth.py", line 44, in amstool
    auth_resp = Auth().update(environment)
  File "/usr/local/lib/python3.10/site-packages/lib/ims.py", line 30, in update
    auth_resp = self.get_browser_cookie(bb_env)
  File "/usr/local/lib/python3.10/site-packages/lib/ims.py", line 54, in get_browser_cookie
    msc_cookie = browser_cookie3.load(domain_name=bb_url)
  File "/usr/local/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 897, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "/usr/local/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 888, in safari
    return Safari(cookie_file, domain_name).load()
  File "/usr/local/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 823, in load
    for cookie in self.__parse_page(i):
  File "/usr/local/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 818, in __parse_page
    yield self.__parse_cookie(page, offset)
  File "/usr/local/lib/python3.10/site-packages/browser_cookie3/__init__.py", line 791, in __parse_cookie
    assert page.read(8) == b'\x00' * 8, self.NEW_ISSUE_MESSAGE
AssertionError: Page format changed.
Please create a new issue on: https://github.com/borisbabic/browser_cookie3/issues/new

**Comment by leoleepsyche** [comment]
when I import other packages which import "browser_cookie3.load()", it faced the same problems. please let me know if there is a method to solve this issue.

**Comment by rafiibrahim8** [comment]
hey @leoleepsyche,
It looks like the safari cookie structure has been changed. And it is causing the problem. Instead of using  `browser_cookie3.load()`, explicitly load cookies for each browser like: `browser_cookie3.chrome()`.
I hope it helps.

**Comment by leoleepsyche** [comment]
> hey @leoleepsyche, It looks like the safari cookie structure has been changed. And it is causing the problem. Instead of using `browser_cookie3.load()`, explicitly load cookies for each browser like: `browser_cookie3.chrome()`. I hope it helps.

thank you so much. I will try it. if it works I will report it here.

**Comment by leoleepsyche** [comment]
> hey @leoleepsyche, It looks like the safari cookie structure has been changed. And it is causing the problem. Instead of using `browser_cookie3.load()`, explicitly load cookies for each browser like: `browser_cookie3.chrome()`. I hope it helps.
Hi, @rafiibrahim8 
Thanks for your help. your solution is helpful. I solved this problem when I modified the coding like this browser_cookie3.chrome(). although I don't know why it worked. But it does solve my problems.  Thank you so much!!!

**Comment by shatyuka** [comment]
Try this PR #147 :)

**Comment by rafiibrahim8** [comment]
Fixed in 0.16.4
