### ISSUE TITLE
0.16.4: Load fails as Safari can't be found on Windows 

### ISSUE THREAD

**Issue by Lordfirespeed** [borisbabic/browser_cookie3#148]
Python 3.11.1
Windows 10 64 bit
browser-cookie3==0.16.4

```
>>> import browser_cookie3
>>> browser_cookie3.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "venv311\Lib\site-packages\browser_cookie3\__init__.py", line 905, in load
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv311\Lib\site-packages\browser_cookie3\__init__.py", line 896, in safari
    return Safari(cookie_file, domain_name).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv311\Lib\site-packages\browser_cookie3\__init__.py", line 735, in __init__
    self.__open_file(cookie_file)
  File "venv311\Lib\site-packages\browser_cookie3\__init__.py", line 745, in __open_file
    if not os.path.exists(cookie_file):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 19, in exists
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
>>>
```

Attempting to use the generic `.load` method on Windows fails due to looking for Safari cookies.

**Comment by rafiibrahim8** [comment]
@Lordfirespeed Thank you for letting us know. The new version [0.16.5](https://pypi.org/project/browser-cookie3/0.16.5/) has been published with the fix.
