### ISSUE TITLE
"ValueError: invalid padding byte" on Linux with google-chrome-stable-68

### ISSUE THREAD

**Issue by xjvs** [borisbabic/browser_cookie3#16]
ENV:
Host: Fedora 28 x86_64
chrome version: google-chrome-stable-68.0.3440.106-1.x86_64
browser_cookies: browser-cookie3==0.6.4

reproduce steps:

1. google-chrome-stable --user-data-dir=/tmp/browser_cookie3
2. visit https://www.theverge.com/

before test, update browser_cookie3 code:

```
diff --git a/__init__.py b/__init__.py
index 1f404b8..6a13fde 100644
--- a/__init__.py
+++ b/__init__.py
@@ -180,7 +180,7 @@ class Chrome:
         if sys.platform == 'win32':
             return self._decrypt_windows_chrome(value, encrypted_value)
 
-        if value or (encrypted_value[:3] != b'v10'):
+        if value or (encrypted_value[:3] not in (b'v10', b'v11')):
             return value
```

test script:

```
import browser_cookie3
cj = browser_cookie3.chrome(cookie_file="/tmp/browser_cookie3/Default/Cookies", domain_name="theverge.com")
```

result:
$ python test_browser_cookie3.py
```
Traceback (most recent call last):
  File "test_browser_cookie3.py", line 3, in <module>
    cj = browser_cookie3.chrome(cookie_file="/tmp/browser_cookie3/Default/Cookies", domain_name="theverge.com")
  File "/home/test/.virtualenvs/chrome3/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 277, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "/home/test/.virtualenvs/chrome3/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 157, in load
    value = self._decrypt(item[5], item[6])
  File "/home/test/.virtualenvs/chrome3/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 195, in _decrypt
    decrypted += cipher.feed()
  File "/home/test/.virtualenvs/chrome3/lib/python3.6/site-packages/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/home/test/.virtualenvs/chrome3/lib/python3.6/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/home/test/.virtualenvs/chrome3/lib/python3.6/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte
```

**Comment by xjvs** [comment]
And I printed the name and encrypted_value as below:

```
chorus_optimize_tracker_id = b'v11\x02\xa1pWQ\x96\xe4\xad\x9a\x0cx\'\xb0\xf3\xed\xfd-\xfa\x92\xcf\xb5vF\xae\xec\x9f\x8c\xce\x0c\x9d[\xe4g!\xf6\xd3\xc7x"\xb2\xf6Q1s\x1d\x11\xa6#'
chorus_optimize_depth3 = b'v11\x02%[\xf4\x82N\xe4\x0b\r\xa9\xa6\x98\xfc\xb3\x0c7'
_chorus_geoip_continent = b'v11x\x1c\xe2\xa5\x81\xdaE\x0c%YU\x86\xacq\x97\x19'
_vm_suid = b"v11\x10\x85g\x1e\xf0E7\xc6\xbe\xe9Y'Z\xfe\xc6\xb7BE\xact\xf5\x7f\xadi\x89i\xc5\r\xc7\xadRof\xe2\xac)\x17\xc6l\xcaD\xd1e\xf5\x9b\xd8\xa2E"
_vm_uid = b"v11&\xb8\x85\xb83\xc0)'e~\x01\xe9\x97\xcd\xa9n\xd7\x97\xbe\xe9\x0b\x9d\xb1z\x7f{\x98\xec\x878\x80\xab5\xa3\xe8VQVD\xf4\x02\xf9\x05Z\x89eT\xec"
AMP_TOKEN = b'v11oxS-\xe3\xe9\xf6%%t!\xe1\xca\xe6\xc7\xb2'
_dc_gtm_UA-26533115-1 = b'v11\x82P\x81\x91\xa3\x12\x07)F\x1e\x1cu\x99\x9f{Q'
_ga = b'v11\xf9m\xad\xe0\x1f"r1\xce<\x96\xd3\xe0\xeaT\x1dt]\xd9\x17\xbaq\xccI\t\x93\xf7\x13d\xe8h\x91'
_gid = b'v11\xcbqH\x11\xc7\xd5\x06!\xf2\xe4+\xb5\x92d\x8d>y\xb7\x15v\xeaB\xe6\xe5\x1ec\xb6y\xde\xfelD'
chorus_optimize_session = b'v11\x94\xae\xe5\xcd\xbb\x0eo}\xdbm\x85\x0cu\xe5\x14}\xf4\x89 p\x87\x8c\x8f\xe1\x15\x13\x07\x85\x0b\xce\xa0\xda\xaf\xcd\xd5\xe6\xf5\xcc`\x9e\xa1\x1a\xc8z\x8c\xe8\xe7>'
```

**Comment by borisbabic** [comment]
I couldn't reproduce this with 68.0.3440.106 on NixOS. Could you please upload the cookie file?

**Comment by borisbabic** [comment]
Are you using a  DE (desktop environment), if so which one (kde, gnome,etc..)? The issue may be that chrome is using the keystore from the DE. This package doesn't yet support using those keystores.   
 
You can test for that by adding `--password-store=basic` when running chrome. If it works like that then the issue is probably the unsupported keystore.

**Comment by xjvs** [comment]
Sorry for late feedback, you're right, I'm using Gnome Desktop 3, it works with chrome option  `--password-store=basic`.

**Comment by borisbabic** [comment]
Is using `--password-store=basic` acceptable for your current use case? I do want to add support for gnome and kde, but I don't currently consider it a priority because there is a workaround which should cover most use cases.

**Comment by xjvs** [comment]
Yes, it's acceptable for me. I have a script to login a site with a fresh new chrome profile, and then read cookies from that, so it doesn't matter for me to use basic password or gnome-keyring.

**Comment by xjvs** [comment]
I'm closing this issue, though it may be good to support other password-store in the future when you get time for it :-)

**Comment by AlaaProg** [comment]
**same problem with chromium browser** 
**i found here problem when get password.i change default value to `chromium`**
`my_pass = get_linux_pass(browser='chromium').encode('utf8')`
