### ISSUE TITLE
Can not load cookie from Firefox on macOS Monterey - unable to open database file

### ISSUE THREAD

**Issue by placentiusz** [borisbabic/browser_cookie3#166]
Can not load cookie from Firefox 
OS: macOS Monterey
Python: 3.9.15
browser_cookie3 version: 0.18.0
 
import browser_cookie3
cj = browser_cookie3.firefox(domain_name='somesite.pl')

Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Users/project/venv/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 1020, in firefox
    return Firefox(cookie_file, domain_name).load()
  File "/Users/project/venv/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 828, in load
    con = _sqlite3_connect_readonly(self.cookie_file)
  File "/Users/project/venv/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 152, in _sqlite3_connect_readonly
    raise ex
  File "/Users/project/venv/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 147, in _sqlite3_connect_readonly
    con.cursor().execute('select 1 from sqlite_master')
sqlite3.OperationalError: unable to open database file

**Comment by stagrim** [comment]
Same error on Linux.

OS: Arch Linux
Python: 3.11.3
browser_cookie3 version: 0.18.0
Firefox Developer Edition: 113.0b9


```Traceback (most recent call last):
  File "...", line 19, in <module>
    main()
  File "...", line 7, in main
    for cookie in browser_cookie3.firefox(cookie_file=<file>, domain_name=<site>):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1020, in firefox
    return Firefox(cookie_file, domain_name).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 828, in load
    con = _sqlite3_connect_readonly(self.cookie_file)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../.local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 152, in _sqlite3_connect_readonly
    raise ex
  File "/home/.../.local/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 147, in _sqlite3_connect_readonly
    con.cursor().execute('select 1 from sqlite_master')
sqlite3.OperationalError: unable to open database file
```


Seems to work fine when the browser is closed

**Comment by natehardison** [comment]
I am having the same issue on macOS Ventura 13.3.1 when calling `browser_cookie3.load(...)` even when Firefox isn't open. Downgrading to `browser_cookie3==0.17.1` solves the issue for me, and makes me suspect this commit https://github.com/borisbabic/browser_cookie3/pull/163/commits/0de4a26899b2f061b59bd28a812327cfb830f70a.

**Comment by rafiibrahim8** [comment]
I'm working on it.

**Comment by rafiibrahim8** [comment]
The new version [0.18.1](https://pypi.org/project/browser-cookie3/0.18.1/) should fix the issue.
