### ISSUE TITLE
FileNotFoundError when LibreWolf profile dir not found

### ISSUE THREAD

**Issue by natehardison** [borisbabic/browser_cookie3#181]
I am on macOS Ventura 13.4. I don't have LibreWolf installed. Fresh install of `browser_cookie3==0.19.0` gives me the following error:

```python
Python 3.11.1 (main, Jan 25 2023, 12:27:45) [Clang 14.0.0 (clang-1400.0.29.102)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import browser_cookie3
>>> browser_cookie3.load("foo.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nateh/testenv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1233, in load
    for cookie in cookie_fn(domain_name=domain_name):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/testenv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1216, in librewolf
    return LibreWolf(cookie_file, domain_name).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/testenv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 1022, in __init__
    super().__init__('LibreWolf', cookie_file, domain_name, **args)
  File "/Users/nateh/testenv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 850, in __init__
    self.cookie_file = cookie_file or self.__find_cookie_file(**kwargs)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/testenv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 910, in __find_cookie_file
    user_data_path = self.__expand_and_check_path(osx_data_dirs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nateh/testenv/lib/python3.11/site-packages/browser_cookie3/__init__.py", line 903, in __expand_and_check_path
    raise FileNotFoundError(
FileNotFoundError: Could not find LibreWolf profile directory
```

**Comment by rafiibrahim8** [comment]
Fixed on version [0.19.1](https://pypi.org/project/browser-cookie3/0.19.1/).
Thank you for reporting :yellow_heart:
