### ISSUE TITLE
OverflowError and OSError for chrome

### ISSUE THREAD

**Issue by dzhuang** [borisbabic/browser_cookie3#35]
It raises `OverflowError` for cookie with  `epoch_start = 1601-01-01 00:00:00 19055414 days`

```
Traceback (most recent call last):
  File "F:/dev/hdchinaLogin/login.py", line 5, in <module>
    cj = browser_cookie3.chrome()
  File "C:\Users\dzhuang\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 345, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "C:\Users\dzhuang\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 173, in load
    expires = epoch_start + delta
OverflowError: date value out of range
```

Also, it raise `OSError` for `expires` without timestamp.

```
Traceback (most recent call last):
  File "F:/dev/hdchinaLogin/login.py", line 5, in <module>
    cj = browser_cookie3.chrome()
  File "C:\Users\dzhuang\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 345, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "C:\Users\dzhuang\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 174, in load
    expires = expires.timestamp()
OSError: [Errno 22] Invalid argument
```

**Comment by borisbabic** [comment]
This should be fixed in >=0.10.1
