### ISSUE TITLE
Chrome 80.0.3987 and above.

### ISSUE THREAD

**Issue by agent666** [borisbabic/browser_cookie3#44]
2020-02-04 Chrome updated  to 80.0.3987 and browser_cookie3 can't get cookies from chrome now (Windows).
Is it possible to fix?

**Comment by borisbabic** [comment]
Could you give more details? What happens?

**Comment by agent666** [comment]
```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    cj = browser_cookie3.load()
  File "C:\Users\irro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\browser_cookie3\__init__.py", line 367, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "C:\Users\irro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\browser_cookie3\__init__.py", line 350, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "C:\Users\irro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\browser_cookie3\__init__.py", line 177, in load
    value = self._decrypt(item[5], item[6])
  File "C:\Users\irro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\browser_cookie3\__init__.py", line 201, in _decrypt
    return self._decrypt_windows_chrome(value, encrypted_value)
  File "C:\Users\irro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\browser_cookie3\__init__.py", line 192, in _decrypt_windows_chrome
    _, data = crypt_unprotect_data(encrypted_value)
  File "C:\Users\irro\AppData\Local\Programs\Python\Python37-32\lib\site-packages\browser_cookie3\__init__.py", line 94, in crypt_unprotect_data
    raise RuntimeError('Failed to decrypt the cipher text with DPAPI')
RuntimeError: Failed to decrypt the cipher text with DPAPI
```

**Comment by brooksmcmillin** [comment]
Chrome did make a change with how cookies work in Chrome 80. I'm not sure if that's the issue here, but I wouldn't be surprised. I'm getting the same error with the same Chrome version. 

https://www.forbes.com/sites/kateoflahertyuk/2020/02/05/new-google-alert-as-experts-warn-chrome-80-cookie-changes-could-break-websites/#34acc0107714

**Comment by brooksmcmillin** [comment]
It looks like a change in the encryption method was included. The mimikatz upgraded their c code to fix it. (DPAPI -> AES-256-GCM with a global AES key protected by DPAPI).

I'm playing around with editing the browser_cookie3 code but I don't know that I am familiar enough with these processes to do it anytime soon. Will update if I get anywhere.

https://twitter.com/gentilkiwi/status/1226112497259876353

**Comment by brooksmcmillin** [comment]
My pull request should fix this, I have it working both with Chrome v80 as well as the previous versions (at least v79) in Windows. 

https://github.com/borisbabic/browser_cookie3/pull/47

**Comment by borisbabic** [comment]
This should be fixed in >=0.10.1

**Comment by giserjing** [comment]
https://stackoverflow.com/questions/43987779/python-module-crypto-cipher-aes-has-no-attribute-mode-ccm-even-though-pycry

**Comment by giserjing** [comment]
I have also been troubled by this problem for a long time, and I solved it by referring to this answer:[module 'Crypto.Cipher.AES' has no attribute 'MODE_CCM' even though pycrypto installed](https://stackoverflow.com/questions/43987779/python-module-crypto-cipher-aes-has-no-attribute-mode-ccm-even-though-pycry)
