### ISSUE TITLE
Python 3.9 installation problem

### ISSUE THREAD

**Issue by Salvora** [borisbabic/browser_cookie3#67]
I updated my python installation from 3.8.x to 3.9.0. After that I tried to install browser_cookie3 for the new python but I am getting error.
```
ERROR: Command errored out with exit status 1:
     command: 'c:\users\laxar\appdata\local\programs\python\python39\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\laxar\\AppData\\Local\\Temp\\pip-install-c4hdj2qm\\pycryptodome\\setup.py'"'"'; __file__='"'"'C:\\Users\\laxar\\AppData\\Local\\Temp\\pip-install-c4hdj2qm\\pycryptodome\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\laxar\AppData\Local\Temp\pip-pip-egg-info-saxvw177'
         cwd: C:\Users\laxar\AppData\Local\Temp\pip-install-c4hdj2qm\pycryptodome\
    Complete output (20 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\laxar\AppData\Local\Temp\pip-install-c4hdj2qm\pycryptodome\setup.py", line 457, in <module>
        set_compiler_options(package_root, ext_modules)
      File "C:\Users\laxar\AppData\Local\Temp\pip-install-c4hdj2qm\pycryptodome\compiler_opt.py", line 341, in set_compiler_options
        clang = compiler_is_clang()
      File "C:\Users\laxar\AppData\Local\Temp\pip-install-c4hdj2qm\pycryptodome\compiler_opt.py", line 251, in compiler_is_clang
        return test_compilation(source, msg="clang")
      File "C:\Users\laxar\AppData\Local\Temp\pip-install-c4hdj2qm\pycryptodome\compiler_opt.py", line 82, in test_compilation
        objects = compiler.compile([fname], extra_postargs=extra_cc_options)
      File "c:\users\laxar\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 323, in compile
        self.initialize()
      File "c:\users\laxar\appdata\local\programs\python\python39\lib\distutils\_msvccompiler.py", line 220, in initialize
        vc_env = _get_vc_env(plat_spec)
      File "c:\users\laxar\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 314, in msvc14_get_vc_env
        return _msvc14_get_vc_env(plat_spec)
      File "c:\users\laxar\appdata\local\programs\python\python39\lib\site-packages\setuptools\msvc.py", line 268, in _msvc14_get_vc_env
        raise distutils.errors.DistutilsPlatformError(
    distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
    Testing support for clang
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
I have 2015-2019 redistributable installed.
Is it not compatible with 3.9?

**Comment by priyanshuga** [comment]
Even I am getting the same error when I downgraded my python version from 3.9 to 3.8.X it works like charm.

**Comment by Mrcubix** [comment]
work without issue on my side in 3.9.0, so it's not related to the python version
