### ISSUE TITLE
Chrome cookie failed on linux

### ISSUE THREAD

**Issue by rafiibrahim8** [borisbabic/browser_cookie3#68]
browser_cookie3 can not load cookies from Chrome on Linux. It throws following exception:

```
Traceback (most recent call last):
  File "/home/ibrahim/Workspace/BrowserCookie/bc.py", line 2, in <module>
    c = bc3.chrome(domain_name='facebook.com')
  File "/home/ibrahim/.local/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 485, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "/home/ibrahim/.local/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 177, in __init__
    my_pass = get_linux_pass(name)
  File "/home/ibrahim/.local/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 117, in get_linux_pass
    gi.require_version("Secret", "1")
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
```

**OS:** elementary OS 5.1.7 Hera x86_64
**Chrome Version:** 87.0.4280.88 (Official Build) (64-bit)

**Comment by cljnnn** [comment]
I have the same issue. Has anyone resolved this?

**Comment by rafiibrahim8** [comment]
@cljnnn There is a pull request(#70) open fixing this issue. Hope it will get merged soon. In the meantime, you can build from source to get around this problem. 
```bash
python3 -m pip uninstall browser-cookie3
python3 -m pip install git+https://github.com/rafiibrahim8/browser_cookie3.git@wild_dev
```

**Comment by cljnnn** [comment]
@rafiibrahim8, Thanks for help. 

I tried it, but I got new error:
Traceback (most recent call last):
   File "/usr/local/lib/python3.6/dist-packages/secretstorage/__init__.py", line 72, in dbus_init
     connection = open_dbus_connection()
   File "/usr/local/lib/python3.6/dist-packages/jeepney/io/blocking.py", line 243, in open_dbus_connection
     bus_addr = get_bus(bus)
   File "/usr/local/lib/python3.6/dist-packages/jeepney/bus.py", line 53, in get_bus
     return find_session_bus()
   File "/usr/local/lib/python3.6/dist-packages/jeepney/bus.py", line 43, in find_session_bus
     return next(get_connectable_addresses(addr))
   File "/usr/local/lib/python3.6/dist-packages/jeepney/bus.py", line 25, in get_connectable_addresses
     for transport, kv in parse_addresses(addr):
   File "/usr/local/lib/python3.6/dist-packages/jeepney/bus.py", line 13, in parse_addresses
     transport, info = addr.split(':', 1)
 ValueError: not enough values to unpack (expected 2, got 1)

Anyway, Thanks very much, I run a chrome in docker, this environment may have more issues.

**Comment by rafiibrahim8** [comment]
@cljnnn Have you tried running it on the main OS?
