### ISSUE TITLE
chrome new update

### ISSUE THREAD

**Issue by shinonomechan** [borisbabic/browser_cookie3#78]
can u release a new update for chrome version 90

**Comment by rafiibrahim8** [comment]
@shinonomechan Can you provide your system details?

**Comment by specman333** [comment]
I guess I encounter the same problem with shinonomechan. The browser_cookie3 code worked very well before. But after chrome updated to v90，it always report error like this：

Traceback (most recent call last):
  File "C:\Users\lili\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 268, in load
    'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))
sqlite3.OperationalError: no such column: secure
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\lili\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 592, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "C:\Users\lili\AppData\Roaming\Python\Python37\site-packages\browser_cookie3\__init__.py", line 272, in load
    'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))

**Comment by specman333** [comment]
I checked my browser_cookie3 version, it is the latest 0.12.0, thanks.

**Comment by shinonomechan** [comment]
Traceback (most recent call last):
  File "C:\Users\kuuko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\browser_cookie3\__init__.py", line 267, in load
    cur.execute('SELECT host_key, path, secure, expires_utc, name, value, encrypted_value '
sqlite3.OperationalError: no such column: secure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\git\js\asd.py", line 2, in <module>
    cj = browser_cookie3.chrome()
  File "C:\Users\kuuko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\browser_cookie3\__init__.py", line 592, in chrome
    return Chrome(cookie_file, domain_name, key_file).load()
  File "C:\Users\kuuko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\browser_cookie3\__init__.py", line 271, in load
    cur.execute('SELECT host_key, path, is_secure, expires_utc, name, value, encrypted_value '
sqlite3.OperationalError: Could not decode to UTF-8 column 'encrypted_value' with text 'v10��9����y���oZ�g�}����B���JW�������H�W'
Exception ignored in: <function ChromiumBased.__del__ at 0x03807C88>
Traceback (most recent call last):
  File "C:\Users\kuuko\AppData\Local\Programs\Python\Python38-32\lib\site-packages\browser_cookie3\__init__.py", line 255, in __del__
    os.remove(self.tmp_cookie_file)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\kuuko\\AppData\\Local\\Temp\\tmp04gcqwdm.sqlite'

this was the error from mine

**Comment by rafiibrahim8** [comment]
@shinonomechan @specman333 I tried on my PC but can not reproduce it. Can you share your system details? Like, OS name and version, python version, etc.

**Comment by rafiibrahim8** [comment]
@shinonomechan @specman333 Can you check if [this fix](https://github.com/rafiibrahim8/browser_cookie3/blob/34e7e99ddc39184cd9039444163a818cfe539118/__init__.py) works? As I can not reproduce it on my machine, I can not test it. But according to the traceback you provided, this should work.

**Comment by shinonomechan** [comment]
@rafiibrahim8 alright hwait

**Comment by shinonomechan** [comment]
ohhh thanks @rafiibrahim8 this works for me

**Comment by specman333** [comment]
> @shinonomechan @specman333 Can you check if [this fix](https://github.com/rafiibrahim8/browser_cookie3/blob/34e7e99ddc39184cd9039444163a818cfe539118/__init__.py) works? As I can not reproduce it on my machine, I can not test it. But according to the traceback you provided, this should work.

Thanks a lot, it worked good!

**Comment by rafiibrahim8** [comment]
@shinonomechan @specman333 can you provide your python version? Also, it will be helpful if you provide the name and the version of your OS.

**Comment by specman333** [comment]
My env: python 3.7.6, OS: Win10 Family 1909， thanks!
