### ISSUE TITLE
Error "browser_cookie3.BrowserCookieError: Can not find cookie file at: bitbucket.org" when get cookie from Chrome on Windows

### ISSUE THREAD

**Issue by saccohuo** [borisbabic/browser_cookie3#9]
```python
﻿import browser_cookie3
import sqlite3
cj = browser_cookie3.chrome('bitbucket.org')
r = requests.get(url, cookies=cj)
get_title(r.content)
```    
I used the above code to get cookie of `Bitbucket` from Chrome. But I got the following error after I REPL to the 3rd line.
Environment: Windows 7 x64, Python 3.6, browser-cookie3 0.6.1,  Chrome 59.0.3071.115 64bit
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 242, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "c:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 105, in __init__
    self.tmp_cookie_file = create_local_copy(cookie_file)
  File "c:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 41, in create_local_copy
    raise BrowserCookieError('Can not find cookie file at: ' + cookie_file)
browser_cookie3.BrowserCookieError: Can not find cookie file at: bitbucket.org
```

**Comment by borisbabic** [comment]
What version of browser_cookie3 are you using? Could you try it with the latest two versions (0.6.0 and 0.6.1)?

**Comment by saccohuo** [comment]
I am using version 0.6.1 of browser_cookie3, and I saw the PR which said that the package is compatible with Chrome on Windows.
So I don't what the test environment of the PR is.

**Comment by borisbabic** [comment]
This looks like a README issue, could you please try the following:

```python
import browser_cookie3
import sqlite3
cj = browser_cookie3.chrome(domain_name='bitbucket.org')
r = requests.get(url, cookies=cj)
get_title(r.content)
```

**Comment by saccohuo** [comment]
After executing the third line, I got the following error.
```
>>> cj = browser_cookie3.chrome(domain_name='bitbucket.org')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 242, in
 chrome
    return Chrome(cookie_file, domain_name).load()
  File "C:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 125, in
 load
    value = self._decrypt(item[5], item[6])
  File "C:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 148, in
 _decrypt
    return self._decrypt_windows_chrome(value, encrypted_value)
  File "C:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 139, in
 _decrypt_windows_chrome
    _, data = CryptUnprotectData(encrypted_value)
  File "C:\Python36\lib\site-packages\browser_cookie3\__init__.py", line 69, in
CryptUnprotectData
    raise RuntimeError('Failed to decrypt the cipher text with DPAPI')
RuntimeError: Failed to decrypt the cipher text with DPAPI
```

**Comment by CryoByte33** [comment]
I am getting the same issue here:

```
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import browser_cookie3
>>> cj = browser_cookie3.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 273, in load
    for cookie in cookie_fn(domain_name=domain_name):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 258, in chrome
    return Chrome(cookie_file, domain_name).load()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/browser_cookie3/__init__.py", line 137, in load
    'FROM cookies WHERE host_key like "%{}%";'.format(self.domain_name))
sqlite3.OperationalError: no such table: cookies
```
I'm using chrome as I type here, and am using browser-cookie3 0.6.2.

**Comment by borisbabic** [comment]
That does not appear to be the same issue. Could you try using [this](https://ufile.io/ti5ok) cookie file and checking if it works for you?

**Comment by borisbabic** [comment]
Is this issue still present?

**Comment by borisbabic** [comment]
If this issue is still present please open a new issue
