### ISSUE TITLE
Brave on ManjaroOs | Unable to get key for cookie decryption

### ISSUE THREAD

**Issue by keyiflerolsun** [borisbabic/browser_cookie3#99]
**OS:** _Manjaro Linux x86_64_
**Kernel:** _5.10.70-1-MANJARO_
**DE:** _Plasma 5.22.5_
**Brave:** _1.30.87 Chromium: 94.0.4606.71 (Official Compilation 64 bit) Version_

```bash
Python 3.9.7 (default, Aug 31 2021, 13:28:12) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import browser_cookie3
>>> cj = browser_cookie3.brave()
Traceback (most recent call last):
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 358, in _decrypt
    decrypted += cipher.feed()
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/pyaes/blockfeeder.py", line 169, in feed
    result = self._final(self._buffer, self._padding)
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/pyaes/blockfeeder.py", line 77, in _block_final_decrypt
    return strip_PKCS7_padding(self.decrypt(data))
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/pyaes/util.py", line 58, in strip_PKCS7_padding
    raise ValueError("invalid padding byte")
ValueError: invalid padding byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 658, in brave
    return Brave(cookie_file, domain_name, key_file).load()
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 297, in load
    value = self._decrypt(item[5], item[6])
  File "/home/keyiflerolsun/.local/lib/python3.9/site-packages/browser_cookie3/__init__.py", line 360, in _decrypt
    raise BrowserCookieError('Unable to get key for cookie decryption')
browser_cookie3.BrowserCookieError: Unable to get key for cookie decryption
```

**Comment by rafiibrahim8** [comment]
KDE uses KWallet for storing the symmetric key used for encryption. I have tried obtaining the key. But somehow it was not possible. For now, try using Gnome Keyring.

**Comment by ppwwyyxx** [comment]
I'm experiencing the same issue using 0.14.2. 

Environment: 
Operating System: Arch Linux
KDE Plasma Version: 5.24.5
KDE Frameworks Version: 5.94.0

When trying to get any cookie I got the same stacktrace as the original issue.
I can confirm that `get_linux_pass` returns an empty string, which seems to be consistent with what https://github.com/borisbabic/browser_cookie3/pull/129 says. However, the decryption still fails.

**Comment by rafiibrahim8** [comment]
Hi @ppwwyyxx,
It seems strange I have the same environment as yours. Mine works fine. 

Can you kindly do the following:
##### Run chrome from a terminal as:
```
google-chrome-stable --enable-logging --v=1
```
You will find a `chrome_debug.log` file in `~/.config/google-chrome`
Can you upload the file somewhere so I can see it?

**Comment by ppwwyyxx** [comment]
@rafiibrahim8 thanks for your comment. I have the log file but it's very large so I'm concerned that it contains private information. Could you kindly let me know what types of information you're looking for?

I did see the following in case it's useful.
```
$cat /t/chrome_debug.log | grep KDE -C 3
[435398:435428:0610/115154.827700:VERBOSE1:media_stream_manager.cc(915)] MSM::InitializeMaybeAsync([this=0x147c0074b080])
[435398:435428:0610/115154.827778:VERBOSE1:media_stream_manager.cc(915)] MDM::MediaDevicesManager()
[435398:435428:0610/115154.827787:VERBOSE1:media_stream_manager.cc(915)] MSM::MediaStreamManager([this=0x147c0074b080]))
[435398:435398:0610/115154.828259:VERBOSE1:key_storage_util_linux.cc(54)] Password storage detected desktop environment: KDE5
[435398:435398:0610/115154.828283:VERBOSE1:key_storage_linux.cc(123)] Selected backend for OSCrypt: KWALLET5
[435398:435398:0610/115154.830335:VERBOSE1:key_storage_linux.cc(206)] OSCrypt using KWallet as backend.
[435398:435398:0610/115154.831045:VERBOSE1:bus.cc(708)] Requested to remove an unknown filter function: 1 with associated data: 0x147c008d6d80
```

**Comment by ppwwyyxx** [comment]
If I create a new user directory with `google-chrome-stable --user-data-dir=debug` then 
`c = browser_cookie3.chrome("./debug/Default/Cookies")` can work correctly. Somehow my original directory does not work.

**Comment by ppwwyyxx** [comment]
I have found the reason. According to chromium source code here: https://source.chromium.org/chromium/chromium/src/+/main:components/os_crypt/os_crypt_linux.cc;l=177-185;drc=18028015e9e3f7085d20882a71148a3b81e2034e

```
  if (base::StartsWith(ciphertext, kObfuscationPrefixV10,
                       base::CompareCase::SENSITIVE)) {
    encryption_key = GetPasswordV10();
    obfuscation_prefix = kObfuscationPrefixV10;
  } else if (base::StartsWith(ciphertext, kObfuscationPrefixV11,
                              base::CompareCase::SENSITIVE)) {
    encryption_key = GetPasswordV11();
    obfuscation_prefix = kObfuscationPrefixV11;
  } else {

```

The correct decryption logic is:
* if encrypted text startswith "v10", use "peanuts" as key.
* if encrypted text startswith "v11", get key from key storage

However this project only uses one key from key storage. It should implement the above logic to correctly decrypt all cookies.

When I printed out the encrypted text in https://github.com/borisbabic/browser_cookie3/blob/0f3104e9ac218b2979edc047ecbbbc86acba1a31/__init__.py#L368, I can see that indeed my cookies have a mixture of v10 and v11.

**Comment by ppwwyyxx** [comment]
Sent a PR: https://github.com/borisbabic/browser_cookie3/pull/130

**Comment by rafiibrahim8** [comment]
Hi @ppwwyyxx,
Thank you so much for giving the time and effort to figure this out. I have reviewed #130. But there are some issues that need to be resolved. 
Please take a look at my review on #130.
